name: stroll_fe_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sunset-final.png
    - assets/images/joey.jpg
    - assets/icons/card.svg
    - assets/icons/bonfire.svg
    - assets/icons/message.svg
    - assets/icons/user.svg